persona_extraction_task:
  description: >
    Analyze the text in input file to identify and understand the different
    users described within. For each user type identified, extract
    distinct characteristics, attributes, roles, and any other relevant
    information that can be used to create a user persona. Focus on
    interpreting the text to infer user traits even if they are not
    explicitly stated.
  expected_output: >
    A structured list of user types identified in the file, with a summary
    of key characteristics and attributes for each type. This summary
    should include inferred traits and behaviors based on the textual
    descriptions.
  agent: persona_extractor

persona_generation_task:
  description: >
    Based on the extracted information, generate 5-6 distinct detailed user personas. 
    Each user person should only contain a name, title, background, work responsibilities, goals, frustrations and needs. The responsibilities, goals, frustrations, 
    needs should relate to real-world scenarios and be consistent with the information extracted from the input text.
  expected_output: >
    A set of 5-6 detailed user persona profiles, each presented as a concise
    narrative with key attributes clearly defined and each attribute having atleast 2 sentences of description.
  agent: persona_generator

# persona_validation_task:
#   description: >
#     Review the generated user personas. Ensure they are consistent with the
#     extracted information, complete, and realistically represent the users
#     described in the input text. Identify and correct any inconsistencies
#     or omissions.
#   expected_output: >
#     A validated set of user personas, confirmed to be accurate, complete, and
#     consistent with the source text. A summary of any corrections or
#     adjustments made during the validation process.
#   agent: persona_validator